language: java
sudo: true

jdk:
  - oraclejdk7
  - oraclejdk8

services:
  - docker

after_success:
  - mvn clean verify jacoco:report coveralls:report -Pcoverage -Dmaven.build.timestamp.format=yyMMddHHmm
