language: java
sudo: required

install: true

jdk:
  - oraclejdk7
  - oraclejdk8

script: mvn clean verify -Pcoverage -Ddocker.showLogs -B

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash -c)
